# Generated by Django 4.2.7 on 2023-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_post_publication_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publication_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
